
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: backend
  namespace: sam
spec:
  routes:
    - order: 0
      predicates:
        - Path=/api/**
      uri: "http://backend:8080"
      filters:
      - StripPrefix=0