
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: frontend
  namespace: sam
spec:
  routes:
    - order: 1
      predicates:
        - Path=/**
      uri: "http://frontend:8080"
      filters:
      - StripPrefix=0