---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway
  namespace: sam
  # labels:
  #   app.kubernetes.io/part-of: sam
spec:
  count: 1
  service:
    type: ClusterIP