apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: backend
  namespace: sam
  labels:
    app.kubernetes.io/part-of: gateway-reference
    apps.tanzu.vmware.com/workload-type: server
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/p-ssanders/gateway-reference-system.git
    subPath: backend
#  serviceClaims:
#    - name: postgres
#      ref:
#        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#        kind: ResourceClaim
#        name: postgres-demo
